//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace epplus.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Areas()
        {
            this.AreaQuarterStatistics = new HashSet<AreaQuarterStatistics>();
            this.Areas1 = new HashSet<Areas>();
            this.IndustriesBasicDatas = new HashSet<IndustriesBasicDatas>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string AreaCode { get; set; }
        public int DelFlag { get; set; }
        public Nullable<System.Guid> ParentRegionID { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaQuarterStatistics> AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Areas> Areas1 { get; set; }
        public virtual Areas Areas2 { get; set; }
        public virtual BasicGdpDatas BasicGdpDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustriesBasicDatas> IndustriesBasicDatas { get; set; }
        public virtual PrimaryIndustries PrimaryIndustries { get; set; }
        public virtual QuotaTrades QuotaTrades { get; set; }
        public virtual SmallScaleIndustries SmallScaleIndustries { get; set; }
    }
}
