//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace epplus.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LargeWholesaleAndRetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LargeWholesaleAndRetails()
        {
            this.LargeWholesaleAndRetailDatas = new HashSet<LargeWholesaleAndRetailDatas>();
        }
    
        public System.Guid Id { get; set; }
        public decimal SelfEmployedAmount { get; set; }
        public decimal SelfEmployedCorrespondingPeriodAmount { get; set; }
        public decimal EnterpriseAmount { get; set; }
        public decimal EnterpriseCorrespondingPeriodAmount { get; set; }
        public System.Guid AreaQuarterStatisticId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual AreaQuarterStatistics AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeWholesaleAndRetailDatas> LargeWholesaleAndRetailDatas { get; set; }
    }
}
