//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace epplus.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GdpStatisticEntities : DbContext
    {
        public GdpStatisticEntities()
            : base("name=GdpStatisticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AreaQuarterStatistics> AreaQuarterStatistics { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<BasicGdpDataItemRecords> BasicGdpDataItemRecords { get; set; }
        public virtual DbSet<BasicGdpDataItems> BasicGdpDataItems { get; set; }
        public virtual DbSet<BasicGdpDataRecords> BasicGdpDataRecords { get; set; }
        public virtual DbSet<BasicGdpDatas> BasicGdpDatas { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ConstructionIndustries> ConstructionIndustries { get; set; }
        public virtual DbSet<ConstructionIndustryDatas> ConstructionIndustryDatas { get; set; }
        public virtual DbSet<CropAccounts> CropAccounts { get; set; }
        public virtual DbSet<Crops> Crops { get; set; }
        public virtual DbSet<Enterprises> Enterprises { get; set; }
        public virtual DbSet<EstateDatas> EstateDatas { get; set; }
        public virtual DbSet<EstatePractitionerDatas> EstatePractitionerDatas { get; set; }
        public virtual DbSet<EstatePractitioners> EstatePractitioners { get; set; }
        public virtual DbSet<Estates> Estates { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Industries> Industries { get; set; }
        public virtual DbSet<IndustriesBasicDatas> IndustriesBasicDatas { get; set; }
        public virtual DbSet<IndustryIncrements> IndustryIncrements { get; set; }
        public virtual DbSet<LargeAccommodationCateringDatas> LargeAccommodationCateringDatas { get; set; }
        public virtual DbSet<LargeAccommodationCaterings> LargeAccommodationCaterings { get; set; }
        public virtual DbSet<LargeIndustrialDatas> LargeIndustrialDatas { get; set; }
        public virtual DbSet<LargeIndustrials> LargeIndustrials { get; set; }
        public virtual DbSet<LargeWholesaleAndRetailDatas> LargeWholesaleAndRetailDatas { get; set; }
        public virtual DbSet<LargeWholesaleAndRetails> LargeWholesaleAndRetails { get; set; }
        public virtual DbSet<LimitedCompanies> LimitedCompanies { get; set; }
        public virtual DbSet<PrimaryIndustries> PrimaryIndustries { get; set; }
        public virtual DbSet<PrimaryIndustryBaseIncrements> PrimaryIndustryBaseIncrements { get; set; }
        public virtual DbSet<PrimaryIndustryRecords> PrimaryIndustryRecords { get; set; }
        public virtual DbSet<QuarterStatistics> QuarterStatistics { get; set; }
        public virtual DbSet<QuotaTradeRecords> QuotaTradeRecords { get; set; }
        public virtual DbSet<QuotaTrades> QuotaTrades { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<SmallScaleIndustries> SmallScaleIndustries { get; set; }
        public virtual DbSet<SmallScaleIndustryRecords> SmallScaleIndustryRecords { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<UserRoleRLs> UserRoleRLs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTagRLs> UserTagRLs { get; set; }
        public virtual DbSet<Varieties> Varieties { get; set; }
    }
}
