//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace epplus.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterStatistics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuarterStatistics()
        {
            this.AreaQuarterStatistics = new HashSet<AreaQuarterStatistics>();
            this.ConstructionIndustryDatas = new HashSet<ConstructionIndustryDatas>();
            this.IndustriesBasicDatas = new HashSet<IndustriesBasicDatas>();
            this.IndustryIncrements = new HashSet<IndustryIncrements>();
            this.PrimaryIndustryBaseIncrements = new HashSet<PrimaryIndustryBaseIncrements>();
        }
    
        public System.Guid Id { get; set; }
        public string QuarterName { get; set; }
        public int QuarterYear { get; set; }
        public int Quarter { get; set; }
        public int Status { get; set; }
        public int Delflag { get; set; }
        public System.DateTime StrTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> EndStatusTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaQuarterStatistics> AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionIndustryDatas> ConstructionIndustryDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustriesBasicDatas> IndustriesBasicDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustryIncrements> IndustryIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryIndustryBaseIncrements> PrimaryIndustryBaseIncrements { get; set; }
    }
}
