//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMapperTest.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaQuarterStatistics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaQuarterStatistics()
        {
            this.BasicGdpDataRecords = new HashSet<BasicGdpDataRecords>();
            this.BasicGdpDatas = new HashSet<BasicGdpDatas>();
            this.PrimaryIndustryRecords = new HashSet<PrimaryIndustryRecords>();
            this.QuotaTradeRecords = new HashSet<QuotaTradeRecords>();
            this.SmallScaleIndustryRecords = new HashSet<SmallScaleIndustryRecords>();
        }
    
        public System.Guid Id { get; set; }
        public string QuarterName { get; set; }
        public int QuarterYear { get; set; }
        public int Quarter { get; set; }
        public int Status { get; set; }
        public int Delflag { get; set; }
        public string ControllerName { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid AreaId { get; set; }
        public System.Guid QuarterStatisticId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual QuarterStatistics QuarterStatistics { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpDataRecords> BasicGdpDataRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpDatas> BasicGdpDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryIndustryRecords> PrimaryIndustryRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotaTradeRecords> QuotaTradeRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmallScaleIndustryRecords> SmallScaleIndustryRecords { get; set; }
    }
}
