//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMapperTest.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropAccounts
    {
        public System.Guid Id { get; set; }
        public string CropName { get; set; }
        public System.Guid CropId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Yields { get; set; }
        public System.Guid PrimaryIndustryRecordId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual Crops Crops { get; set; }
        public virtual PrimaryIndustryRecords PrimaryIndustryRecords { get; set; }
    }
}
