//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMapperTest.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprises
    {
        public System.Guid Id { get; set; }
        public System.Guid SmallScaleIndustryRecordId { get; set; }
        public string IndustryCode { get; set; }
        public string PhoneNum { get; set; }
        public string OrganizationCode { get; set; }
        public string LegalPersonCode { get; set; }
        public string EnterpriseName { get; set; }
        public decimal Amount { get; set; }
        public decimal CorrespondingPeriodAmount { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual SmallScaleIndustryRecords SmallScaleIndustryRecords { get; set; }
    }
}
