//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBook
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<System.Guid> AdminId { get; set; }
        public string UserName { get; set; }
        public string UserNamePY { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Email { get; set; }
        public string LinkTel { get; set; }
        public string Birthday { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string WorkUnit { get; set; }
        public string WorkTel { get; set; }
        public string WorkFunction { get; set; }
        public string WorkDepartment { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
