//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEf.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartTownEntities : DbContext
    {
        public SmartTownEntities()
            : base("name=SmartTownEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AddressBook> AddressBook { get; set; }
        public virtual DbSet<AddressBookGroup> AddressBookGroup { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Checklist> Checklist { get; set; }
        public virtual DbSet<Dictionary> Dictionary { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<Issue> Issue { get; set; }
        public virtual DbSet<JPushInfo> JPushInfo { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<RoleResource> RoleResource { get; set; }
        public  DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WorkFlow> WorkFlow { get; set; }
        public virtual DbSet<WorkFlowInstance> WorkFlowInstance { get; set; }
        public virtual DbSet<WorkFlowInstanceProcess> WorkFlowInstanceProcess { get; set; }
        public virtual DbSet<WorkFlowInstanceProcessIdea> WorkFlowInstanceProcessIdea { get; set; }
        public virtual DbSet<WorkFlowStep> WorkFlowStep { get; set; }
        public virtual DbSet<WorkFlowStepButtons> WorkFlowStepButtons { get; set; }
        public virtual DbSet<WorkFlowType> WorkFlowType { get; set; }
        public virtual DbSet<WorkInstruction> WorkInstruction { get; set; }
        public virtual DbSet<DepartPosition> DepartPosition { get; set; }
    }
}
