//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace testEf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public int Gender { get; set; }
        public string NickName { get; set; }
        public string QQ { get; set; }
        public string WeiChat { get; set; }
        public string IdentityNumber { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public string DutyId { get; set; }
        public string DepartmentId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string ImgUrl { get; set; }
        public int IsAcceptSystemMsg { get; set; }
        public string RegistrationId { get; set; }
    }
}
