//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaReportLogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaReportLogs()
        {
            this.BasicGdpReportLogRLs = new HashSet<BasicGdpReportLogRLs>();
            this.PrimaryReportLogRLs = new HashSet<PrimaryReportLogRLs>();
            this.QuotaReprotLogRLs = new HashSet<QuotaReprotLogRLs>();
            this.SmallScaleReportLogRLs = new HashSet<SmallScaleReportLogRLs>();
        }
    
        public System.Guid Id { get; set; }
        public string OperationName { get; set; }
        public string OperationDescribe { get; set; }
        public string Remark { get; set; }
        public int DealWithFlag { get; set; }
        public int OperationKind { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpReportLogRLs> BasicGdpReportLogRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryReportLogRLs> PrimaryReportLogRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotaReprotLogRLs> QuotaReprotLogRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmallScaleReportLogRLs> SmallScaleReportLogRLs { get; set; }
    }
}
