//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaQuarterStatistics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AreaQuarterStatistics()
        {
            this.AccountingHistoricalDatas = new HashSet<AccountingHistoricalDatas>();
            this.BasicGdpDataRecords = new HashSet<BasicGdpDataRecords>();
            this.ConstructionIndustries = new HashSet<ConstructionIndustries>();
            this.EstatePractitioners = new HashSet<EstatePractitioners>();
            this.Estates = new HashSet<Estates>();
            this.LargeAccommodationCaterings = new HashSet<LargeAccommodationCaterings>();
            this.LargeIndustrials = new HashSet<LargeIndustrials>();
            this.LargeWholesaleAndRetails = new HashSet<LargeWholesaleAndRetails>();
            this.PrimaryIndustryRecords = new HashSet<PrimaryIndustryRecords>();
            this.QuotaTradeRecords = new HashSet<QuotaTradeRecords>();
            this.SmallScaleIndustryRecords = new HashSet<SmallScaleIndustryRecords>();
        }
    
        public System.Guid Id { get; set; }
        public string QuarterName { get; set; }
        public int QuarterYear { get; set; }
        public int Quarter { get; set; }
        public int Rank { get; set; }
        public Nullable<decimal> ApprovedOutputValue { get; set; }
        public Nullable<decimal> ApprovedGrowth { get; set; }
        public Nullable<decimal> Growth { get; set; }
        public Nullable<decimal> OutputValue { get; set; }
        public int Status { get; set; }
        public int ExtractSubmitStatus { get; set; }
        public int GdpAccountingStatus { get; set; }
        public int GdpApprovedStatus { get; set; }
        public int Delflag { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public System.Guid AreaId { get; set; }
        public System.DateTime StrTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> EndStatusTime { get; set; }
        public Nullable<System.Guid> QuarterStatisticId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingHistoricalDatas> AccountingHistoricalDatas { get; set; }
        public virtual Areas Areas { get; set; }
        public virtual QuarterStatistics QuarterStatistics { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpDataRecords> BasicGdpDataRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionIndustries> ConstructionIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatePractitioners> EstatePractitioners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estates> Estates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeAccommodationCaterings> LargeAccommodationCaterings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeIndustrials> LargeIndustrials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeWholesaleAndRetails> LargeWholesaleAndRetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryIndustryRecords> PrimaryIndustryRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotaTradeRecords> QuotaTradeRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmallScaleIndustryRecords> SmallScaleIndustryRecords { get; set; }
    }
}
