//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicGdpDataItemRecords
    {
        public System.Guid Id { get; set; }
        public string ItemName { get; set; }
        public int ItemType { get; set; }
        public int Type { get; set; }
        public int Delflag { get; set; }
        public int Unit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CorrespondingPeriodAmount { get; set; }
        public System.Guid BasicGdpDataItemId { get; set; }
        public System.Guid BasicGdpDataRecordId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual BasicGdpDataItems BasicGdpDataItems { get; set; }
        public virtual BasicGdpDataRecords BasicGdpDataRecords { get; set; }
    }
}
