//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicGdpDataRecords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BasicGdpDataRecords()
        {
            this.BasicGdpDataItemRecords = new HashSet<BasicGdpDataItemRecords>();
            this.BasicGdpReportLogRLs = new HashSet<BasicGdpReportLogRLs>();
        }
    
        public System.Guid Id { get; set; }
        public string ReportName { get; set; }
        public int SubmitStatus { get; set; }
        public int Delflag { get; set; }
        public int ApplyDelay { get; set; }
        public int DelayStatus { get; set; }
        public string ResponsibleForUser { get; set; }
        public string ResponsibleForPhone { get; set; }
        public string ChargeUser { get; set; }
        public int ApplyDelayDay { get; set; }
        public int DelayDay { get; set; }
        public Nullable<System.DateTime> Lastreporttime { get; set; }
        public Nullable<int> ReportTimes { get; set; }
        public string Reasonsapplication { get; set; }
        public System.Guid AreaQuarterStatisticId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual AreaQuarterStatistics AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpDataItemRecords> BasicGdpDataItemRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpReportLogRLs> BasicGdpReportLogRLs { get; set; }
    }
}
