//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtractPublicBasicDatas
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> val1 { get; set; }
        public Nullable<decimal> val2 { get; set; }
        public Nullable<decimal> val3 { get; set; }
        public Nullable<decimal> val4 { get; set; }
        public Nullable<decimal> val5 { get; set; }
        public Nullable<decimal> val6 { get; set; }
        public Nullable<decimal> val7 { get; set; }
        public Nullable<decimal> val8 { get; set; }
        public Nullable<decimal> val9 { get; set; }
        public Nullable<decimal> val10 { get; set; }
        public Nullable<System.Guid> QuarterStatisticId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual QuarterStatistics QuarterStatistics { get; set; }
    }
}
