//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayerItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LayerItems()
        {
            this.ItemLayerPermissionKindRls = new HashSet<ItemLayerPermissionKindRls>();
            this.LayerItemRoleRLs = new HashSet<LayerItemRoleRLs>();
            this.LayerItems1 = new HashSet<LayerItems>();
        }
    
        public int LayerId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string LayerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLayerPermissionKindRls> ItemLayerPermissionKindRls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayerItemRoleRLs> LayerItemRoleRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LayerItems> LayerItems1 { get; set; }
        public virtual LayerItems LayerItems2 { get; set; }
    }
}
