//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GdpStatisticEntities1 : DbContext
    {
        public GdpStatisticEntities1()
            : base("name=GdpStatisticEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccommodationCateringSummaryBasics> AccommodationCateringSummaryBasics { get; set; }
        public virtual DbSet<AccountingHistoricalDatas> AccountingHistoricalDatas { get; set; }
        public virtual DbSet<AccountingHistoricalItems> AccountingHistoricalItems { get; set; }
        public virtual DbSet<AreaQuarterStatistics> AreaQuarterStatistics { get; set; }
        public virtual DbSet<AreaReportLogs> AreaReportLogs { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<BasicGdpDataItemRecords> BasicGdpDataItemRecords { get; set; }
        public virtual DbSet<BasicGdpDataItems> BasicGdpDataItems { get; set; }
        public virtual DbSet<BasicGdpDataRecords> BasicGdpDataRecords { get; set; }
        public virtual DbSet<BasicGdpDatas> BasicGdpDatas { get; set; }
        public virtual DbSet<BasicGdpDataUserRLs> BasicGdpDataUserRLs { get; set; }
        public virtual DbSet<BasicGdpReportLogRLs> BasicGdpReportLogRLs { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ConstructionIndustries> ConstructionIndustries { get; set; }
        public virtual DbSet<ConstructionIndustryDatas> ConstructionIndustryDatas { get; set; }
        public virtual DbSet<CropAccounts> CropAccounts { get; set; }
        public virtual DbSet<Crops> Crops { get; set; }
        public virtual DbSet<DataAcquisitionStatus> DataAcquisitionStatus { get; set; }
        public virtual DbSet<Enterprises> Enterprises { get; set; }
        public virtual DbSet<EstateDatas> EstateDatas { get; set; }
        public virtual DbSet<EstatePractitionerDatas> EstatePractitionerDatas { get; set; }
        public virtual DbSet<EstatePractitioners> EstatePractitioners { get; set; }
        public virtual DbSet<Estates> Estates { get; set; }
        public virtual DbSet<ExtractExcursusQuotas> ExtractExcursusQuotas { get; set; }
        public virtual DbSet<ExtractPublicBasicDatas> ExtractPublicBasicDatas { get; set; }
        public virtual DbSet<ExtractQuotaCoefficients> ExtractQuotaCoefficients { get; set; }
        public virtual DbSet<GDPApprovedBaseDatas> GDPApprovedBaseDatas { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<IndustrialParentDatas> IndustrialParentDatas { get; set; }
        public virtual DbSet<Industries> Industries { get; set; }
        public virtual DbSet<IndustriesBasicDatas> IndustriesBasicDatas { get; set; }
        public virtual DbSet<IndustryIncrements> IndustryIncrements { get; set; }
        public virtual DbSet<ItemLayerPermissionKindRls> ItemLayerPermissionKindRls { get; set; }
        public virtual DbSet<LargeAccommodationCateringDatas> LargeAccommodationCateringDatas { get; set; }
        public virtual DbSet<LargeAccommodationCaterings> LargeAccommodationCaterings { get; set; }
        public virtual DbSet<LargeIndustrialDatas> LargeIndustrialDatas { get; set; }
        public virtual DbSet<LargeIndustrials> LargeIndustrials { get; set; }
        public virtual DbSet<LargeWholesaleAndRetailDatas> LargeWholesaleAndRetailDatas { get; set; }
        public virtual DbSet<LargeWholesaleAndRetails> LargeWholesaleAndRetails { get; set; }
        public virtual DbSet<LayerItemRoleRLs> LayerItemRoleRLs { get; set; }
        public virtual DbSet<LayerItems> LayerItems { get; set; }
        public virtual DbSet<LimitedCompanies> LimitedCompanies { get; set; }
        public virtual DbSet<PermissionKinds> PermissionKinds { get; set; }
        public virtual DbSet<PrimaryIndustries> PrimaryIndustries { get; set; }
        public virtual DbSet<PrimaryIndustryBaseIncrements> PrimaryIndustryBaseIncrements { get; set; }
        public virtual DbSet<PrimaryIndustryRecords> PrimaryIndustryRecords { get; set; }
        public virtual DbSet<PrimaryIndustryUserRLs> PrimaryIndustryUserRLs { get; set; }
        public virtual DbSet<PrimaryReportLogRLs> PrimaryReportLogRLs { get; set; }
        public virtual DbSet<QuarterStatistics> QuarterStatistics { get; set; }
        public virtual DbSet<QuotaReprotLogRLs> QuotaReprotLogRLs { get; set; }
        public virtual DbSet<QuotaTradeRecords> QuotaTradeRecords { get; set; }
        public virtual DbSet<QuotaTrades> QuotaTrades { get; set; }
        public virtual DbSet<QuotaTradeUserRLs> QuotaTradeUserRLs { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<SmallScaleIndustries> SmallScaleIndustries { get; set; }
        public virtual DbSet<SmallScaleIndustryRecords> SmallScaleIndustryRecords { get; set; }
        public virtual DbSet<SmallScaleIndustryUserRLs> SmallScaleIndustryUserRLs { get; set; }
        public virtual DbSet<SmallScaleReportLogRLs> SmallScaleReportLogRLs { get; set; }
        public virtual DbSet<SummaryConstructionIndustryBasics> SummaryConstructionIndustryBasics { get; set; }
        public virtual DbSet<SummaryDepositLoanBalanceBasics> SummaryDepositLoanBalanceBasics { get; set; }
        public virtual DbSet<SummaryNonProfitServiceBasics> SummaryNonProfitServiceBasics { get; set; }
        public virtual DbSet<SummaryPermanentPopulationBasics> SummaryPermanentPopulationBasics { get; set; }
        public virtual DbSet<SummaryStatusSubmits> SummaryStatusSubmits { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<UserRoleRLs> UserRoleRLs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTagRLs> UserTagRLs { get; set; }
        public virtual DbSet<Varieties> Varieties { get; set; }
        public virtual DbSet<WholesaleAndRetailSummaryBasics> WholesaleAndRetailSummaryBasics { get; set; }
    }
}
