//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterStatistics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuarterStatistics()
        {
            this.AccommodationCateringSummaryBasics = new HashSet<AccommodationCateringSummaryBasics>();
            this.AreaQuarterStatistics = new HashSet<AreaQuarterStatistics>();
            this.ConstructionIndustryDatas = new HashSet<ConstructionIndustryDatas>();
            this.DataAcquisitionStatus = new HashSet<DataAcquisitionStatus>();
            this.EstateDatas = new HashSet<EstateDatas>();
            this.EstatePractitionerDatas = new HashSet<EstatePractitionerDatas>();
            this.ExtractExcursusQuotas = new HashSet<ExtractExcursusQuotas>();
            this.ExtractPublicBasicDatas = new HashSet<ExtractPublicBasicDatas>();
            this.ExtractQuotaCoefficients = new HashSet<ExtractQuotaCoefficients>();
            this.GDPApprovedBaseDatas = new HashSet<GDPApprovedBaseDatas>();
            this.IndustrialParentDatas = new HashSet<IndustrialParentDatas>();
            this.IndustriesBasicDatas = new HashSet<IndustriesBasicDatas>();
            this.IndustryIncrements = new HashSet<IndustryIncrements>();
            this.LargeAccommodationCateringDatas = new HashSet<LargeAccommodationCateringDatas>();
            this.LargeIndustrialDatas = new HashSet<LargeIndustrialDatas>();
            this.LargeWholesaleAndRetailDatas = new HashSet<LargeWholesaleAndRetailDatas>();
            this.PrimaryIndustryBaseIncrements = new HashSet<PrimaryIndustryBaseIncrements>();
            this.SummaryConstructionIndustryBasics = new HashSet<SummaryConstructionIndustryBasics>();
            this.SummaryDepositLoanBalanceBasics = new HashSet<SummaryDepositLoanBalanceBasics>();
            this.SummaryNonProfitServiceBasics = new HashSet<SummaryNonProfitServiceBasics>();
            this.SummaryPermanentPopulationBasics = new HashSet<SummaryPermanentPopulationBasics>();
            this.SummaryStatusSubmits = new HashSet<SummaryStatusSubmits>();
            this.WholesaleAndRetailSummaryBasics = new HashSet<WholesaleAndRetailSummaryBasics>();
        }
    
        public System.Guid Id { get; set; }
        public string QuarterName { get; set; }
        public int QuarterYear { get; set; }
        public int Quarter { get; set; }
        public int Status { get; set; }
        public int OverStatus { get; set; }
        public int Delflag { get; set; }
        public System.DateTime StrTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<System.DateTime> EndStatusTime { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccommodationCateringSummaryBasics> AccommodationCateringSummaryBasics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaQuarterStatistics> AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionIndustryDatas> ConstructionIndustryDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataAcquisitionStatus> DataAcquisitionStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstateDatas> EstateDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatePractitionerDatas> EstatePractitionerDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtractExcursusQuotas> ExtractExcursusQuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtractPublicBasicDatas> ExtractPublicBasicDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtractQuotaCoefficients> ExtractQuotaCoefficients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GDPApprovedBaseDatas> GDPApprovedBaseDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustrialParentDatas> IndustrialParentDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustriesBasicDatas> IndustriesBasicDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndustryIncrements> IndustryIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeAccommodationCateringDatas> LargeAccommodationCateringDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeIndustrialDatas> LargeIndustrialDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LargeWholesaleAndRetailDatas> LargeWholesaleAndRetailDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryIndustryBaseIncrements> PrimaryIndustryBaseIncrements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryConstructionIndustryBasics> SummaryConstructionIndustryBasics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryDepositLoanBalanceBasics> SummaryDepositLoanBalanceBasics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryNonProfitServiceBasics> SummaryNonProfitServiceBasics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryPermanentPopulationBasics> SummaryPermanentPopulationBasics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SummaryStatusSubmits> SummaryStatusSubmits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WholesaleAndRetailSummaryBasics> WholesaleAndRetailSummaryBasics { get; set; }
    }
}
