//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotaTradeRecords
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuotaTradeRecords()
        {
            this.LimitedCompanies = new HashSet<LimitedCompanies>();
            this.QuotaReprotLogRLs = new HashSet<QuotaReprotLogRLs>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> Lastreporttime { get; set; }
        public string QuotaTradeName { get; set; }
        public Nullable<int> WholesaleAndRetailCount { get; set; }
        public Nullable<int> WholesaleAndRetailCorrespondingPeriodCount { get; set; }
        public Nullable<int> WholesaleAndRetailEmployeeAvgCount { get; set; }
        public Nullable<int> WholesaleAndRetailEmployeeAvgCorrespondingPeriodCount { get; set; }
        public Nullable<int> AccommodationCateringCount { get; set; }
        public Nullable<int> AccommodationCateringCorrespondingPeriodCount { get; set; }
        public Nullable<int> AccommodationCateringEmployeeAvgCount { get; set; }
        public Nullable<int> AccommodationCateringEmployeeAvgCorrespondingPeriodCount { get; set; }
        public string ResponsibleForUser { get; set; }
        public string ResponsibleForPhone { get; set; }
        public string ChargeUser { get; set; }
        public System.Guid AreaQuarterStatisticId { get; set; }
        public int SubmitStatus { get; set; }
        public int Delflag { get; set; }
        public int ApplyDelay { get; set; }
        public int DelayStatus { get; set; }
        public int ApplyDelayDay { get; set; }
        public int DelayDay { get; set; }
        public string Reasonsapplication { get; set; }
        public Nullable<int> ReportTimes { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual AreaQuarterStatistics AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LimitedCompanies> LimitedCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotaReprotLogRLs> QuotaReprotLogRLs { get; set; }
    }
}
