//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryStatusSubmits
    {
        public System.Guid Id { get; set; }
        public int PrimaryIndustryStatus { get; set; }
        public Nullable<System.DateTime> PrimaryIndustrySubmitTime { get; set; }
        public int IndustrialStatus { get; set; }
        public Nullable<System.DateTime> IndustrialSubmitTime { get; set; }
        public int ConstructionIndustryStatus { get; set; }
        public Nullable<System.DateTime> ConstructionIndustrySubmitTime { get; set; }
        public int WholesaleAndRetailStatus { get; set; }
        public Nullable<System.DateTime> WholesaleAndRetailSubmitTime { get; set; }
        public int AccommodationCateringStatus { get; set; }
        public Nullable<System.DateTime> AccommodationCateringSubmitTime { get; set; }
        public int DepositLoanBalanceStatus { get; set; }
        public Nullable<System.DateTime> DepositLoanBalanceSubmitTime { get; set; }
        public int EstateStatus { get; set; }
        public Nullable<System.DateTime> EstateSubmitTime { get; set; }
        public int EstatePractitionerStatus { get; set; }
        public Nullable<System.DateTime> EstatePractitionerSubmitTime { get; set; }
        public int NonProfitServiceStatus { get; set; }
        public Nullable<System.DateTime> NonProfitServiceSubmitTime { get; set; }
        public int PublicServiceStatus { get; set; }
        public Nullable<System.DateTime> PublicServiceSubmitTime { get; set; }
        public int PermanentPopulationStatus { get; set; }
        public Nullable<System.DateTime> PermanentPopulationSubmitTime { get; set; }
        public int RegisteredPopulationStatus { get; set; }
        public Nullable<System.DateTime> RegisteredPopulationSubmitTime { get; set; }
        public Nullable<System.Guid> QuarterStatisticId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        public virtual QuarterStatistics QuarterStatistics { get; set; }
    }
}
