//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GdpTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.AreaQuarterStatistics = new HashSet<AreaQuarterStatistics>();
            this.BasicGdpDatas = new HashSet<BasicGdpDatas>();
            this.BasicGdpDataUserRLs = new HashSet<BasicGdpDataUserRLs>();
            this.Images = new HashSet<Images>();
            this.PrimaryIndustries = new HashSet<PrimaryIndustries>();
            this.PrimaryIndustryUserRLs = new HashSet<PrimaryIndustryUserRLs>();
            this.QuotaTrades = new HashSet<QuotaTrades>();
            this.QuotaTradeUserRLs = new HashSet<QuotaTradeUserRLs>();
            this.SmallScaleIndustries = new HashSet<SmallScaleIndustries>();
            this.SmallScaleIndustryUserRLs = new HashSet<SmallScaleIndustryUserRLs>();
            this.UserRoleRLs = new HashSet<UserRoleRLs>();
            this.UserTagRLs = new HashSet<UserTagRLs>();
        }
    
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string ImageKey { get; set; }
        public int Age { get; set; }
        public string Signature { get; set; }
        public int Gender { get; set; }
        public string RegisterIp { get; set; }
        public string RegisterAddress { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string InternalNotes { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaQuarterStatistics> AreaQuarterStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpDatas> BasicGdpDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasicGdpDataUserRLs> BasicGdpDataUserRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryIndustries> PrimaryIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrimaryIndustryUserRLs> PrimaryIndustryUserRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotaTrades> QuotaTrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotaTradeUserRLs> QuotaTradeUserRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmallScaleIndustries> SmallScaleIndustries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmallScaleIndustryUserRLs> SmallScaleIndustryUserRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleRLs> UserRoleRLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTagRLs> UserTagRLs { get; set; }
    }
}
