//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_CodeFrist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        public System.Guid Identity { get; set; }
        public System.DateTime StrDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal CostUSD { get; set; }
    }
}
