// <auto-generated />
using System;
using EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Migrations
{
    [DbContext(typeof(FristContext))]
    partial class FristContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.Entites.AllLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AllLogs");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AllLog");
                });

            modelBuilder.Entity("EFCore.Entites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Creatime");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFCore.Entites.UserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LogDec");

                    b.Property<DateTime>("LoginTime");

                    b.Property<Guid>("UId");

                    b.HasKey("Id");

                    b.HasIndex("UId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("EFCore.Entites.Log", b =>
                {
                    b.HasBaseType("EFCore.Entites.AllLog");

                    b.Property<string>("Message");

                    b.Property<Guid>("UserLogId");

                    b.HasIndex("UserLogId");

                    b.ToTable("Log");

                    b.HasDiscriminator().HasValue("Log");
                });

            modelBuilder.Entity("EFCore.Entites.User", b =>
                {
                    b.OwnsOne("EFCore.Entites.Pason", "Pason", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<int>("Age");

                            b1.ToTable("Users");

                            b1.HasOne("EFCore.Entites.User")
                                .WithOne("Pason")
                                .HasForeignKey("EFCore.Entites.Pason", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("EFCore.Entites.UserLog", b =>
                {
                    b.HasOne("EFCore.Entites.User", "User")
                        .WithMany("UserLog")
                        .HasForeignKey("UId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EFCore.Entites.Log", b =>
                {
                    b.HasOne("EFCore.Entites.UserLog", "UserLog")
                        .WithMany("Logs")
                        .HasForeignKey("UserLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
